# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x' # or whatever latest version you installed
  displayName: 'Install Node.js'
  

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'
  

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'
    artifactName: 'drop'